### PR TITLE
Make media query to not overlap

### PR DESCRIPTION
**Pull request by limsohee1002**

### CODE REVIEW

**Comment by limsohee1002** [comment]
@conordavidson 
I have one more question about media queries.
```
$breakpoints: (
  "sm": 640px,
  "md": 832px,
  "lg": 1024px,
  "xl": 1152px
);
```

if you have these breakpoints,  if you use `md-up` here, it will generate `min-width: 823px`
if you use `md-down` it will generate `max-width: 1024px - 1px` is it expected behavior?

I am just wondering if we use `md-down` it should be `max-width: 832px - 1px`

**Comment by joshiefishbein** [comment]
@limsohee1002 @conordavidson as I understand it, `md-down` translates in my head to `medium and down`. I would use that media query to make sure that my target breakpoint (`md`) and all smaller breakpoints get certain rules. Let me know if that makes sense.

I think part of my problem with a lot of modern css kits is that the small medium breakpoints are too inclusive and also do not account for one of the most popular tablet-portrait breakpoints: `768px`, which makes the `-down` queries less helpful.

**Comment by joshiefishbein** [comment]
I didn't notice what basement's default breakpoints were because I always overwrite them but I think these breakpoints are way too closely clustered in general:

```
$breakpoints: (
  "sm": 640px,
  "md": 832px,
  "lg": 1024px,
  "xl": 1152px
);
```

Typically, I run along the most common breakpoints:

```
$breakpoints: (
  "xs": 375px,
  "sm": 768px,
  "md": 1024px,
  "lg": 1280px,
  "xl": 1440px
);
```

**Comment by conordavidson** [comment]
> @limsohee1002 @conordavidson as I understand it, `md-down` translates in my head to `medium and down`. I would use that media query to make sure that my target breakpoint (`md`) and all smaller breakpoints get certain rules. Let me know if that makes sense.
> 
> I think part of my problem with a lot of modern css kits is that the small medium breakpoints are too inclusive and also do not account for one of the most popular tablet-portrait breakpoints: `768px`, which makes the `-down` queries less helpful.

This keeps that logic the same. It just means that `md-down` and `md-up` don't overlap. For example:
```
@include media(‘md-down’) {
  color: red;
 };
@include media(‘md-up’) {
  color: blue;
 };
```
will now compile to:
```
@media (max-width: 767px) {
  color: red;
}
@media (min-width: 768px) {
  color: blue;
}
```
Before, both `color: blue` and `color: red` were applied at `768px`.

**Comment by limsohee1002** [comment]
> > @limsohee1002 @conordavidson as I understand it, `md-down` translates in my head to `medium and down`. I would use that media query to make sure that my target breakpoint (`md`) and all smaller breakpoints get certain rules. Let me know if that makes sense.
> > I think part of my problem with a lot of modern css kits is that the small medium breakpoints are too inclusive and also do not account for one of the most popular tablet-portrait breakpoints: `768px`, which makes the `-down` queries less helpful.
> 
> This keeps that logic the same. It just means that `md-down` and `md-up` don't overlap. For example:
> 
> ```
> @include media(‘md-down’) {
>   color: red;
>  };
> @include media(‘md-up’) {
>   color: blue;
>  };
> ```
> 
> will now compile to:
> 
> ```
> @media (max-width: 767px) {
>   color: red;
> }
> @media (min-width: 768px) {
>   color: blue;
> }
> ```
> 
> Before, both `color: blue` and `color: red` were applied at `768px`.

I think currently 

```
@include media(‘md-down’) {
  color: red;
 };
@include media(‘md-up’) {
  color: blue;
 };
```
compile to 

```
@media (max-width: 1024px) {
  color: red;
}
@media (min-width: 768px) {
  color: blue;
}
```
`<breakpoint>-down` seems to take next breakpoint's size

**Pull request merged**
